// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsotoUniWebApp.Models
{
    public partial class Correlation
    {
        private int? _correlationID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CorrelationID
        {
            get { return this._correlationID; }
            set { this._correlationID = value; }
        }
        
        private int? _courseID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CourseID
        {
            get { return this._courseID; }
            set { this._courseID = value; }
        }
        
        private int? _courseWorkID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CourseWorkID
        {
            get { return this._courseWorkID; }
            set { this._courseWorkID = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Correlation class.
        /// </summary>
        public Correlation()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken correlationIDValue = inputObject["CorrelationID"];
                if (correlationIDValue != null && correlationIDValue.Type != JTokenType.Null)
                {
                    this.CorrelationID = ((int)correlationIDValue);
                }
                JToken courseIDValue = inputObject["CourseID"];
                if (courseIDValue != null && courseIDValue.Type != JTokenType.Null)
                {
                    this.CourseID = ((int)courseIDValue);
                }
                JToken courseWorkIDValue = inputObject["CourseWorkID"];
                if (courseWorkIDValue != null && courseWorkIDValue.Type != JTokenType.Null)
                {
                    this.CourseWorkID = ((int)courseWorkIDValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Correlation
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CorrelationID != null)
            {
                outputObject["CorrelationID"] = this.CorrelationID.Value;
            }
            if (this.CourseID != null)
            {
                outputObject["CourseID"] = this.CourseID.Value;
            }
            if (this.CourseWorkID != null)
            {
                outputObject["CourseWorkID"] = this.CourseWorkID.Value;
            }
            return outputObject;
        }
    }
}
