// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsotoUniWebApp.Models;
using Newtonsoft.Json.Linq;

namespace ConsotoUniWebApp.Models
{
    public static partial class CorrelationCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Correlation> DeserializeJson(JToken inputObject)
        {
            IList<Correlation> deserializedObject = new List<Correlation>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Correlation correlation = new Correlation();
                correlation.DeserializeJson(iListValue);
                deserializedObject.Add(correlation);
            }
            return deserializedObject;
        }
    }
}
