// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsotoUniWebApp.Models;
using Newtonsoft.Json.Linq;

namespace ConsotoUniWebApp.Models
{
    public static partial class CourseWorkCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<CourseWork> DeserializeJson(JToken inputObject)
        {
            IList<CourseWork> deserializedObject = new List<CourseWork>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                CourseWork courseWork = new CourseWork();
                courseWork.DeserializeJson(iListValue);
                deserializedObject.Add(courseWork);
            }
            return deserializedObject;
        }
    }
}
