// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using ConsotoUniWebApp;
using Microsoft.Rest;

namespace ConsotoUniWebApp
{
    public partial interface IConsotoUniApi : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        ICorrelations Correlations
        {
            get; 
        }
        
        ICourses Courses
        {
            get; 
        }
        
        ICourseWorks CourseWorks
        {
            get; 
        }
        
        IEnrollments Enrollments
        {
            get; 
        }
        
        IStudents Students
        {
            get; 
        }
    }
}
